package codegen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const MinEnumCollectionLibraryVersion = "0.1.10"

const enumManifestPath = ".codegen/frontend-enums.json"
const enumGeneratedHeader = "// Code generated by cmd/codegen. DO NOT EDIT.\n// Frontend enum: "

type frontendEnumManifest struct {
	Version int      `json:"version"`
	Files   []string `json:"files"`
}

// RenderFrontendEnums owns only the managed enum files listed in its manifest.
// It never scans/deletes unrelated .gen.ts files or manually maintained files.
func (r Renderer) RenderFrontendEnums(objects []ObjectView) error {
	enums := collectFrontendEnums(objects)
	manifestPath := filepath.Join(r.Config.FrontendRoot, filepath.FromSlash(enumManifestPath))
	previous := frontendEnumManifest{Version: 1}
	manifestData, err := os.ReadFile(manifestPath)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("read enum manifest: %w", err)
	}
	if errors.Is(err, fs.ErrNotExist) && len(enums) == 0 {
		return nil // No change at all for projects that have never used enums.
	}
	if err == nil {
		if err := json.Unmarshal(manifestData, &previous); err != nil || previous.Version != 1 {
			return fmt.Errorf("invalid enum ownership manifest %s (expected version 1)", manifestPath)
		}
	}
	for _, name := range previous.Files {
		if !safeEnumArtifactPath(name) {
			return fmt.Errorf("unsafe path %q in enum ownership manifest", name)
		}
	}

	current := frontendEnumManifest{Version: 1, Files: []string{}}
	expected := make(map[string]bool)
	jobs := make([]struct {
		job  RenderJob
		data FrontendEnumView
	}, 0, len(enums)*2)
	for _, enum := range enums {
		for _, kind := range []struct{ dir, template string }{{"types", "enumTypes.ts.tmpl"}, {"schemas", "enumSchemas.ts.tmpl"}} {
			name := path.Join("src", kind.dir, "enums", enum.FileBase+".gen.ts")
			expected[name] = true
			current.Files = append(current.Files, name)
			job := RenderJob{
				TemplatePath: filepath.Join(r.Config.TemplateDir, "vue", kind.template),
				TargetPath:   filepath.Join(r.Config.FrontendRoot, filepath.FromSlash(name)),
				Format:       FormatNone,
			}
			if err := verifyManagedEnumFile(job.TargetPath); err != nil {
				return err
			}
			// Parse/render every enum template before changing ownership or output.
			if _, err := r.executeTemplate(job.TemplatePath, enum); err != nil {
				return err
			}
			jobs = append(jobs, struct {
				job  RenderJob
				data FrontendEnumView
			}{job, enum})
		}
	}
	stale := make([]string, 0)
	for _, name := range previous.Files {
		if expected[name] {
			continue
		}
		target := filepath.Join(r.Config.FrontendRoot, filepath.FromSlash(name))
		if err := verifyManagedEnumFile(target); err != nil {
			return err
		}
		stale = append(stale, target)
	}
	if r.Config.Check && len(stale) > 0 {
		return fmt.Errorf("check failed: stale generated enum artifacts; run codegen generate: %s", strings.Join(stale, ", "))
	}
	for _, item := range jobs {
		if err := r.renderFile(item.job, item.data); err != nil {
			return err
		}
	}
	content, err := json.MarshalIndent(current, "", "\t")
	if err != nil {
		return err
	}
	content = append(content, '\n')
	if r.Config.Check {
		if !bytes.Equal(manifestData, content) {
			return fmt.Errorf("check failed: enum ownership manifest %s is missing or outdated", manifestPath)
		}
		return nil
	}
	for _, target := range stale {
		if err := os.Remove(target); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("remove stale enum %s: %w", target, err)
		}
		fmt.Printf("removed stale generated enum %s\n", target)
	}
	if err := os.MkdirAll(filepath.Dir(manifestPath), 0o755); err != nil {
		return err
	}
	return writeFileAtomic(manifestPath, content, 0o644)
}

func safeEnumArtifactPath(name string) bool {
	if name != path.Clean(name) || strings.Contains(name, "\\") || !strings.HasSuffix(name, ".gen.ts") {
		return false
	}
	return path.Dir(name) == "src/types/enums" || path.Dir(name) == "src/schemas/enums"
}

func verifyManagedEnumFile(target string) error {
	info, err := os.Lstat(target)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("refusing to overwrite/delete non-regular enum artifact %s", target)
	}
	content, err := os.ReadFile(target)
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(content, []byte(enumGeneratedHeader)) {
		return fmt.Errorf("refusing to overwrite/delete developer-owned enum file %s (generated enum header is missing)", target)
	}
	return nil
}

func hasGeneratedEnumColumns(objects []ObjectView) bool {
	for _, object := range objects {
		if !object.Frontend.List.Enabled {
			continue
		}
		for _, column := range object.Frontend.List.Columns {
			if column.EnumDefinition != nil {
				return true
			}
		}
	}
	return false
}

// Codegen does not own package.json. Enforce the feature's minimum version
// without changing an application's dependency policy or lockfile.
func validateEnumCollectionDependency(frontendRoot string, objects []ObjectView) error {
	if !hasGeneratedEnumColumns(objects) {
		return nil
	}
	const packageName = "@katren/vue-collection-lib"
	type packageJSON struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
		Version         string            `json:"version"`
	}
	file := filepath.Join(frontendRoot, "package.json")
	content, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("enum collections require %s >=%s; declare %q: %q in %s: %w", packageName, MinEnumCollectionLibraryVersion, packageName, "^"+MinEnumCollectionLibraryVersion, file, err)
	}
	var pkg packageJSON
	if err := json.Unmarshal(content, &pkg); err != nil {
		return fmt.Errorf("read frontend package.json: %w", err)
	}
	version := pkg.Dependencies[packageName]
	if version == "" {
		version = pkg.DevDependencies[packageName]
	}
	local := strings.HasPrefix(version, "file:") || strings.HasPrefix(version, "link:") || strings.HasPrefix(version, "workspace:")
	compatible := enumLibraryRangeCompatible(strings.TrimPrefix(version, "workspace:"))
	installedFile := filepath.Join(frontendRoot, "node_modules", "@katren", "vue-collection-lib", "package.json")
	if strings.HasPrefix(version, "file:") || strings.HasPrefix(version, "link:") {
		_, location, _ := strings.Cut(version, ":")
		if !filepath.IsAbs(location) {
			location = filepath.Join(frontendRoot, location)
		}
		installedFile = filepath.Join(location, "package.json")
	}
	installed, installedErr := os.ReadFile(installedFile)
	if installedErr == nil {
		var actual packageJSON
		if err := json.Unmarshal(installed, &actual); err != nil {
			return fmt.Errorf("read installed collection library metadata: %w", err)
		}
		if !enumLibraryRangeCompatible(actual.Version) {
			return fmt.Errorf("enum collections require %s >=%s, but %s declares version %q; update/install the frontend dependency", packageName, MinEnumCollectionLibraryVersion, installedFile, actual.Version)
		}
		if local {
			compatible = true
		}
	} else if !errors.Is(installedErr, fs.ErrNotExist) {
		return installedErr
	}
	if !compatible {
		return fmt.Errorf("enum collections require %s >=%s; dependency %q in %s does not establish this minimum. Use ^%s or a local package with a verifiable compatible version", packageName, MinEnumCollectionLibraryVersion, version, file, MinEnumCollectionLibraryVersion)
	}
	return nil
}

var simpleEnumLibraryRange = regexp.MustCompile(`^(?:\^|~|>=\s*)?v?(\d+)\.(\d+)\.(\d+)(?:\+[0-9A-Za-z.-]+)?$`)

func enumLibraryRangeCompatible(version string) bool {
	parts := simpleEnumLibraryRange.FindStringSubmatch(strings.TrimSpace(version))
	if parts == nil {
		return false
	}
	major, majorErr := strconv.Atoi(parts[1])
	minor, minorErr := strconv.Atoi(parts[2])
	patch, patchErr := strconv.Atoi(parts[3])
	if majorErr != nil || minorErr != nil || patchErr != nil {
		return false
	}
	return major > 0 || minor > 1 || (minor == 1 && patch >= 10)
}
